/*
 * File: sfRedis.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand,
 *   you must change it only in the area defined as:
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text'
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  -------------------------------------------------------------------------
 *
 * Created: Fri Aug 09 11:37:51 2024
 */

#define S_FUNCTION_LEVEL               2
#define S_FUNCTION_NAME                sfRedis

/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS                     1

/* Input Port  0 */
#define IN_PORT_0_NAME                 u0
#define INPUT_0_DIMS_ND                {DYNAMICALLY_SIZED,1}
#define INPUT_0_NUM_ELEMS              DYNAMICALLY_SIZED
#define INPUT_0_WIDTH                  DYNAMICALLY_SIZED
#define INPUT_DIMS_0_COL               1
#define INPUT_0_DTYPE                  real_T
#define INPUT_0_COMPLEX                COMPLEX_NO
#define INPUT_0_UNIT                   ""
#define IN_0_BUS_BASED                 0
#define IN_0_BUS_NAME
#define IN_0_DIMS                      1-D
#define INPUT_0_FEEDTHROUGH            1
#define IN_0_ISSIGNED                  0
#define IN_0_WORDLENGTH                8
#define IN_0_FIXPOINTSCALING           1
#define IN_0_FRACTIONLENGTH            9
#define IN_0_BIAS                      0
#define IN_0_SLOPE                     0.125
#define NUM_OUTPUTS                    1

/* Output Port  0 */
#define OUT_PORT_0_NAME                y0
#define OUTPUT_0_DIMS_ND               {DYNAMICALLY_SIZED,1}
#define OUTPUT_0_NUM_ELEMS             DYNAMICALLY_SIZED
#define OUTPUT_0_WIDTH                 DYNAMICALLY_SIZED
#define OUTPUT_DIMS_0_COL              1
#define OUTPUT_0_DTYPE                 real_T
#define OUTPUT_0_COMPLEX               COMPLEX_NO
#define OUTPUT_0_UNIT                  ""
#define OUT_0_BUS_BASED                0
#define OUT_0_BUS_NAME
#define OUT_0_DIMS                     1-D
#define OUT_0_ISSIGNED                 1
#define OUT_0_WORDLENGTH               8
#define OUT_0_FIXPOINTSCALING          1
#define OUT_0_FRACTIONLENGTH           3
#define OUT_0_BIAS                     0
#define OUT_0_SLOPE                    0.125
#define NPARAMS                        3

/* Parameter 0 */
#define PARAMETER_0_NAME               host
#define PARAMETER_0_DTYPE              uint8_T
#define PARAMETER_0_COMPLEX            COMPLEX_NO
#define PARAMETER_0_UNIT               ""

/* Parameter 1 */
#define PARAMETER_1_NAME               port
#define PARAMETER_1_DTYPE              int32_T
#define PARAMETER_1_COMPLEX            COMPLEX_NO
#define PARAMETER_1_UNIT               ""

/* Parameter 2 */
#define PARAMETER_2_NAME               passwd
#define PARAMETER_2_DTYPE              uint8_T
#define PARAMETER_2_COMPLEX            COMPLEX_NO
#define PARAMETER_2_UNIT               ""
#define SAMPLE_TIME_0                  INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES                2
#define DISC_STATES_IC                 [0,0]
#define NUM_CONT_STATES                1
#define CONT_STATES_IC                 [0]
#define SFUNWIZ_GENERATE_TLC           0
#define SOURCEFILES                    "__SFB__LIB_PATH sfHiredis/hiredis_mex/__SFB__hiredis__SFB__libhiredis.dylib"
#define PANELINDEX                     N/A
#define USE_SIMSTRUCT                  1
#define SHOW_COMPILE_STEPS             1
#define CREATE_DEBUG_MEXFILE           1
#define SAVE_CODE_ONLY                 0
#define SFUNWIZ_REVISION               3.0

/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S)                  ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S)                  ssGetSFcnParam(S, 1)
#define PARAM_DEF2(S)                  ssGetSFcnParam(S, 2)
#define IS_PARAM_INT32(pVal)           (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsInt32(pVal))
#define IS_PARAM_UINT8(pVal)           (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsUint8(pVal))

extern void sfRedis_Start_wrapper(real_T *xC,
  real_T *xD,
  void **pW,
  const uint8_T *host, const int_T p_width0,
  const int32_T *port, const int_T p_width1,
  const uint8_T *passwd, const int_T p_width2,
  SimStruct *S);
extern void sfRedis_Outputs_wrapper(const real_T *u0,
  real_T *y0,
  const real_T *xD,
  const real_T *xC,
  void **pW,
  const uint8_T *host, const int_T p_width0,
  const int32_T *port, const int_T p_width1,
  const uint8_T *passwd, const int_T p_width2,
  const int_T y_0_width,
  const int_T u_0_width,
  SimStruct *S);
extern void sfRedis_Update_wrapper(const real_T *u0,
  real_T *y0,
  real_T *xD,
  void **pW,
  const uint8_T *host, const int_T p_width0,
  const int32_T *port, const int_T p_width1,
  const uint8_T *passwd, const int_T p_width2,
  const int_T y_0_width,
  const int_T u_0_width,
  SimStruct *S);
extern void sfRedis_Derivatives_wrapper(const real_T *u0,
  real_T *y0,
  real_T *dx,
  real_T *xC,
  void **pW,
  const uint8_T *host, const int_T p_width0,
  const int32_T *port, const int_T p_width1,
  const uint8_T *passwd, const int_T p_width2,
  const int_T y_0_width,
  const int_T u_0_width,
  SimStruct *S);
extern void sfRedis_Terminate_wrapper(real_T *xC,
  real_T *xD,
  void **pW,
  const uint8_T *host, const int_T p_width0,
  const int32_T *port, const int_T p_width1,
  const uint8_T *passwd, const int_T p_width2,
  SimStruct *S);

/*=============================*
 * Data Transposition Routines *
 *=============================*/
int linear_idx(const int srcdims[], const int numdims, const int dstk)
{
  int idxCurDim;
  int i, j;
  int srck = 0, dstk_remainingDims = dstk;
  for (i=0,j=numdims-1; i<numdims; i++, j--) {
    idxCurDim = dstk_remainingDims % srcdims[j];
    srck = srck * srcdims[j] + idxCurDim;
    dstk_remainingDims = dstk_remainingDims / srcdims[j];
  }

  return srck;
}

mwSize linear_idxmwsize(const mwSize srcdims[], const int numdims, const mwSize
  dstk)
{
  mwSize idxCurDim;
  int i, j;
  mwSize srck = 0;
  mwSize dstk_remainingDims = dstk;
  for (i=0,j=numdims-1; i<numdims; i++, j--) {
    idxCurDim = dstk_remainingDims % srcdims[j];
    srck = srck * srcdims[j] + idxCurDim;
    dstk_remainingDims = dstk_remainingDims / srcdims[j];
  }

  return srck;
}

/*
   A is [N1xN2xN3] and T is [N3xN2xN1]
   A[n1,n2,n3]=T[n3,n2,n1]

   1) Given linear index k = n1+N1*(n2+N2*n3), find [n1,n2,n3]
   2) Compute corresponding linear index k' = n3+N3*(n2+N2*n1)
   3) Use linear index to assign A[k] = T[k']

   Example input:
   src:     A matrix memory pointer
   srcdims: [N1,N2, N3]
   numdims: 3
   dst:     T matrix memory pointer
   elsize:  sizeof(double)/sizeof(char)
 */
void NDTransposeBySrcSpecs(void *dst, const void *src, const int srcdims[],
  const int numdims, const int elsize)
{
  int w = srcdims[0];
  int k;
  for (k = 1; k < numdims; k ++) {
    w *= srcdims[k];
  }

  for (k = 0; k < w; k ++) {
    int sk = linear_idx(srcdims, numdims, k);
    int offset = k * elsize;
    memcpy((char*)dst + k * elsize, (const char*)src + sk * elsize, elsize);
  }
}

/* the data type of srcdims is mwSize*, the data type in original NDTransposeBySrcSpecs is int* */
void NDTransposeBySrcSpecsMwSize(void *dst, const void *src, const mwSize
  srcdims[], const int numdims, const int elsize)
{
  mwSize w = srcdims[0];
  int k;
  mwSize widthIndex;
  for (k = 1; k < numdims; k ++) {
    w *= srcdims[k];
  }

  for (widthIndex = 0; widthIndex < w; widthIndex ++) {
    mwSize sk = linear_idxmwsize(srcdims, numdims, widthIndex);
    memcpy((char*)dst + widthIndex * elsize, (const char*)src + sk * elsize,
           elsize);
  }
}

void NDTransposeByDstSpecs(void *dst, const void *src, const int dstdims[],
  const int numdims, const int elsize)
{
  int w = dstdims[0];
  int k;
  for (k = 1; k < numdims; k ++) {
    w *= dstdims[k];
  }

  for (k = 0; k < w; k ++) {
    int dk = linear_idx(dstdims, numdims, k);
    int offset = k * elsize;
    memcpy((char*)dst + dk * elsize, (const char*)src + k * elsize, elsize);
  }
}

/*====================*
 * S-function methods *
 *====================*/
#if !defined(__LCC__) && (defined(__cplusplus) || (__STDC_VERSION__ >= 199901L))
#define __sfb_snprintf_(msgToWriteTo,size,fmtStr,arg1) snprintf(msgToWriteTo,size,fmtStr,arg1)
#else
#define __sfb_snprintf_(msgToWriteTo,size,fmtStr,arg1) sprintf(msgToWriteTo,fmtStr,arg1)
#endif

#define MDL_CHECK_PARAMETERS
#if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)

/* Function: mdlCheckParameters =============================================
 * Abstract:
 *     Verify parameter definitions and types.
 */
static void mdlCheckParameters(SimStruct *S)
{
  int paramIndex = 0;
  bool invalidParam = false;

  /* All parameters must match the S-function Builder Dialog */
  {
    const mxArray *pVal0 = ssGetSFcnParam(S, 0);
    if (!IS_PARAM_UINT8(pVal0)) {
      invalidParam = true;
      paramIndex = 0;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal1 = ssGetSFcnParam(S, 1);
    if (!IS_PARAM_INT32(pVal1)) {
      invalidParam = true;
      paramIndex = 1;
      goto EXIT_POINT;
    }
  }

  {
    const mxArray *pVal2 = ssGetSFcnParam(S, 2);
    if (!IS_PARAM_UINT8(pVal2)) {
      invalidParam = true;
      paramIndex = 2;
      goto EXIT_POINT;
    }
  }

 EXIT_POINT:
  if (invalidParam) {
    static char parameterErrorMsg[1024];
    __sfb_snprintf_(parameterErrorMsg, 1024,
                    "The data type and or complexity of parameter %d does not match the "
                    "information specified in the S-function Builder dialog. "
                    "For non-double parameters you will need to cast them using int8, int16, "
                    "int32, uint8, uint16, uint32 or boolean.", paramIndex + 1);
    ssSetLocalErrorStatus(S, parameterErrorMsg);
  }

  return;
}

#endif                                 /* MDL_CHECK_PARAMETERS */

/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{
  ssSetNumSFcnParams(S, NPARAMS);      /* Number of expected parameters */

#if defined(MATLAB_MEX_FILE)

  if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
    mdlCheckParameters(S);
    if (ssGetErrorStatus(S) != NULL) {
      return;
    }
  } else {
    return;                            /* Parameter mismatch will be reported by Simulink */
  }

  UnitId pUnitIdReg;
  ssRegisterUnitFromExpr(S, PARAMETER_0_UNIT, &pUnitIdReg);
  if (pUnitIdReg != INVALID_UNIT_ID) {
    ssSetSFcnParamUnit(S, 0, pUnitIdReg);
  } else {
    ssSetLocalErrorStatus(S,
                          "Invalid Unit provided for parameter for S-Function");
    return;
  }

  ssRegisterUnitFromExpr(S, PARAMETER_1_UNIT, &pUnitIdReg);
  if (pUnitIdReg != INVALID_UNIT_ID) {
    ssSetSFcnParamUnit(S, 1, pUnitIdReg);
  } else {
    ssSetLocalErrorStatus(S,
                          "Invalid Unit provided for parameter for S-Function");
    return;
  }

  ssRegisterUnitFromExpr(S, PARAMETER_2_UNIT, &pUnitIdReg);
  if (pUnitIdReg != INVALID_UNIT_ID) {
    ssSetSFcnParamUnit(S, 2, pUnitIdReg);
  } else {
    ssSetLocalErrorStatus(S,
                          "Invalid Unit provided for parameter for S-Function");
    return;
  }

#endif

  ssSetArrayLayoutForCodeGen(S, SS_ROW_MAJOR);
  ssSetOperatingPointCompliance(S, DISALLOW_OPERATING_POINT);
  ssSetNumContStates(S, NUM_CONT_STATES);
  ssSetNumDiscStates(S, NUM_DISC_STATES);
  if (!ssSetNumInputPorts(S, NUM_INPUTS))
    return;

  /* Input Port 0 */
  ssSetInputPortWidth(S, 0, INPUT_0_NUM_ELEMS);
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
  ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
  ssSetInputPortRequiredContiguous(S, 0, 1);/*direct input signal access*/

  /*
   * Configure the Units for Input Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId inUnitIdReg;
    ssRegisterUnitFromExpr(S, INPUT_0_UNIT, &inUnitIdReg);
    if (inUnitIdReg != INVALID_UNIT_ID) {
      ssSetInputPortUnit(S, 0, inUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for input port u0 of S-Function sfRedis");
      return;
    }

#endif

  }

  if (!ssSetNumOutputPorts(S, NUM_OUTPUTS))
    return;

  /* Output Port 0 */
  ssSetOutputPortWidth(S, 0, OUTPUT_0_NUM_ELEMS);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

  /*
   * Configure the Units for Output Ports
   */
  if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {

#if defined(MATLAB_MEX_FILE)

    UnitId outUnitIdReg;
    ssRegisterUnitFromExpr(S, OUTPUT_0_UNIT, &outUnitIdReg);
    if (outUnitIdReg != INVALID_UNIT_ID) {
      ssSetOutputPortUnit(S, 0, outUnitIdReg);
    } else {
      ssSetLocalErrorStatus(S,
                            "Invalid Unit provided for output port y0 of S-Function sfRedis");
      return;
    }

#endif

  }

  if (!ssSetNumDWork(S, 5))
    return;

  /*
   * Configure the dwork 0 (u0_t)
   */
  ssSetDWorkDataType(S, 0, ssGetInputPortDataType(S, 0));
  ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 0, "u0_t");
  ssSetDWorkWidth(S, 0, ssGetInputPortWidth(S, 0));
  ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);

  /*
   * Configure the dwork 1 (y0_t)
   */
  ssSetDWorkDataType(S, 1, ssGetOutputPortDataType(S, 0));
  ssSetDWorkUsageType(S, 1, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 1, "y0_t");
  ssSetDWorkWidth(S, 1, ssGetOutputPortWidth(S, 0));
  ssSetDWorkComplexSignal(S, 1, COMPLEX_NO);

  /*
   * Configure the dwork 2 (host_t)
   */
  DTypeId paramDTypeId_0;
  ssGetSFcnParamDataType(S, 0, &paramDTypeId_0);
  ssSetDWorkDataType(S, 2, paramDTypeId_0);
  ssSetDWorkUsageType(S, 2, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 2, "host_t");
  ssSetDWorkWidth(S, 2, mxGetNumberOfElements(PARAM_DEF0(S)));
  ssSetDWorkComplexSignal(S, 2, COMPLEX_NO);

  /*
   * Configure the dwork 3 (port_t)
   */
  DTypeId paramDTypeId_1;
  ssGetSFcnParamDataType(S, 1, &paramDTypeId_1);
  ssSetDWorkDataType(S, 3, paramDTypeId_1);
  ssSetDWorkUsageType(S, 3, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 3, "port_t");
  ssSetDWorkWidth(S, 3, mxGetNumberOfElements(PARAM_DEF1(S)));
  ssSetDWorkComplexSignal(S, 3, COMPLEX_NO);

  /*
   * Configure the dwork 4 (passwd_t)
   */
  DTypeId paramDTypeId_2;
  ssGetSFcnParamDataType(S, 2, &paramDTypeId_2);
  ssSetDWorkDataType(S, 4, paramDTypeId_2);
  ssSetDWorkUsageType(S, 4, SS_DWORK_USED_AS_SCRATCH);
  ssSetDWorkName(S, 4, "passwd_t");
  ssSetDWorkWidth(S, 4, mxGetNumberOfElements(PARAM_DEF2(S)));
  ssSetDWorkComplexSignal(S, 4, COMPLEX_NO);
  ssSetNumPWork(S, 1400);
  ssSetNumSampleTimes(S, 1);
  ssSetNumRWork(S, 0);
  ssSetNumIWork(S, 0);
  ssSetNumModes(S, 0);
  ssSetNumNonsampledZCs(S, 0);
  ssSetSimulinkVersionGeneratedIn(S, "24.1");

  /* Take care when specifying exception free code - see sfuntmpl_doc.c */
  ssSetRuntimeThreadSafetyCompliance(S, RUNTIME_THREAD_SAFETY_COMPLIANCE_FALSE);
  ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                   SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO

static void mdlSetInputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetInputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)

static void mdlSetOutputPortDimensionInfo(SimStruct *S,
  int_T port,
  const DimsInfo_T *dimsInfo)
{
  if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo))
    return;
}

#endif

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, SAMPLE_TIME_0);
  ssSetModelReferenceSampleTimeDefaultInheritance(S);
  ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_INITIALIZE_CONDITIONS

/* Function: mdlInitializeConditions ========================================
 * Abstract:
 *    Initialize the states
 */
static void mdlInitializeConditions(SimStruct *S)
{
  real_T *xD = ssGetRealDiscStates(S);
  real_T *xC = ssGetContStates(S);

  /* Warning: parameters not of type double used as IC will be replaced with 0.0 */
  xD[0] = 0;
  xD[1] = 0;
  xC[0] = 0;
}

#define MDL_SET_INPUT_PORT_DATA_TYPE

static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE

static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
  ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES

static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType(S, 0, SS_DOUBLE);
  ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{
}

#endif

#define MDL_START                                                /* Change to #undef to remove function */
#if defined(MDL_START)

/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
  void **pW = ssGetPWork(S);
  real_T *xD = ssGetDiscStates(S);
  real_T *xC = ssGetContStates(S);
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const uint8_T *host = (const uint8_T *) mxGetUint8s(PARAM_DEF0(S));
  const int32_T *port = (const int32_T *) mxGetInt32s(PARAM_DEF1(S));
  const uint8_T *passwd = (const uint8_T *) mxGetUint8s(PARAM_DEF2(S));
  uint8_T *host_t = (uint8_T *)ssGetDWork(S, 2);
  int32_T *port_t = (int32_T *)ssGetDWork(S, 3);
  uint8_T *passwd_t = (uint8_T *)ssGetDWork(S, 4);
  NDTransposeBySrcSpecsMwSize((void*)host_t, (const void*)host, mxGetDimensions
    (PARAM_DEF0(S)), mxGetNumberOfDimensions(PARAM_DEF0(S)), sizeof(uint8_T));
  NDTransposeBySrcSpecsMwSize((void*)port_t, (const void*)port, mxGetDimensions
    (PARAM_DEF1(S)), mxGetNumberOfDimensions(PARAM_DEF1(S)), sizeof(int32_T));
  NDTransposeBySrcSpecsMwSize((void*)passwd_t, (const void*)passwd,
    mxGetDimensions (PARAM_DEF2(S)), mxGetNumberOfDimensions(PARAM_DEF2(S)),
    sizeof(uint8_T));
  sfRedis_Start_wrapper(xC, xD, pW, host_t, p_width0, port_t, p_width1, passwd_t,
                        p_width2, S);
}

#endif                                 /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  void **pW = ssGetPWork(S);
  const real_T *u0 = (real_T *) ssGetInputPortRealSignal(S, 0);
  real_T *y0 = (real_T *) ssGetOutputPortRealSignal(S, 0);
  const real_T *xD = ssGetDiscStates(S);
  const real_T *xC = ssGetContStates(S);
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const uint8_T *host = (const uint8_T *) mxGetUint8s(PARAM_DEF0(S));
  const int32_T *port = (const int32_T *) mxGetInt32s(PARAM_DEF1(S));
  const uint8_T *passwd = (const uint8_T *) mxGetUint8s(PARAM_DEF2(S));
  const int_T y_0_width = ssGetOutputPortWidth(S, 0);
  const int_T u_0_width = ssGetInputPortWidth(S, 0);

  /* S-Function Builder Row Major Support has been enabled for custom
   * code, a transposed copy will be created for any array signals.
   */
  real_T *u0_t = (real_T *)ssGetDWork(S, 0);
  real_T *y0_t = (real_T *)ssGetDWork(S, 1);
  uint8_T *host_t = (uint8_T *)ssGetDWork(S, 2);
  int32_T *port_t = (int32_T *)ssGetDWork(S, 3);
  uint8_T *passwd_t = (uint8_T *)ssGetDWork(S, 4);
  NDTransposeBySrcSpecs((void*)u0_t, (const void*)u0, ssGetInputPortDimensions(S,
    0), ssGetInputPortNumDimensions(S, 0), sizeof(real_T));
  NDTransposeBySrcSpecsMwSize((void*)host_t, (const void*)host, mxGetDimensions
    (PARAM_DEF0(S)), mxGetNumberOfDimensions(PARAM_DEF0(S)), sizeof(uint8_T));
  NDTransposeBySrcSpecsMwSize((void*)port_t, (const void*)port, mxGetDimensions
    (PARAM_DEF1(S)), mxGetNumberOfDimensions(PARAM_DEF1(S)), sizeof(int32_T));
  NDTransposeBySrcSpecsMwSize((void*)passwd_t, (const void*)passwd,
    mxGetDimensions (PARAM_DEF2(S)), mxGetNumberOfDimensions(PARAM_DEF2(S)),
    sizeof(uint8_T));
  sfRedis_Outputs_wrapper(u0_t, y0_t, xD, xC, pW, host_t, p_width0, port_t,
    p_width1, passwd_t, p_width2, y_0_width, u_0_width, S);
  NDTransposeByDstSpecs((void*)y0, (const void*)y0_t, ssGetOutputPortDimensions
                        (S, 0), ssGetOutputPortNumDimensions(S, 0), sizeof
                        (real_T));
}

#define MDL_UPDATE                                               /* Change to #undef to remove function */
#if defined(MDL_UPDATE)

/* Function: mdlUpdate ======================================================
 * Abstract:
 *    This function is called once for every major integration time step.
 *    Discrete states are typically updated here, but this function is
 *    useful for performing any tasks that should only take place once per
 *    integration step.
 */
static void mdlUpdate(SimStruct *S, int_T tid)
{
  void **pW = ssGetPWork(S);
  const real_T *u0 = (real_T *) ssGetInputPortRealSignal(S, 0);
  real_T *y0 = (real_T *) ssGetOutputPortRealSignal(S, 0);
  real_T *xD = ssGetDiscStates(S);
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const uint8_T *host = (const uint8_T *) mxGetUint8s(PARAM_DEF0(S));
  const int32_T *port = (const int32_T *) mxGetInt32s(PARAM_DEF1(S));
  const uint8_T *passwd = (const uint8_T *) mxGetUint8s(PARAM_DEF2(S));
  const int_T y_0_width = ssGetOutputPortWidth(S, 0);
  const int_T u_0_width = ssGetInputPortWidth(S, 0);

  /* S-Function Builder Row Major Support has been enabled for custom
   * code, a transposed copy will be created for any array signals.
   */
  real_T *u0_t = (real_T *)ssGetDWork(S, 0);
  real_T *y0_t = (real_T *)ssGetDWork(S, 1);
  uint8_T *host_t = (uint8_T *)ssGetDWork(S, 2);
  int32_T *port_t = (int32_T *)ssGetDWork(S, 3);
  uint8_T *passwd_t = (uint8_T *)ssGetDWork(S, 4);
  NDTransposeBySrcSpecs((void*)u0_t, (const void*)u0, ssGetInputPortDimensions(S,
    0), ssGetInputPortNumDimensions(S, 0), sizeof(real_T));
  NDTransposeBySrcSpecsMwSize((void*)host_t, (const void*)host, mxGetDimensions
    (PARAM_DEF0(S)), mxGetNumberOfDimensions(PARAM_DEF0(S)), sizeof(uint8_T));
  NDTransposeBySrcSpecsMwSize((void*)port_t, (const void*)port, mxGetDimensions
    (PARAM_DEF1(S)), mxGetNumberOfDimensions(PARAM_DEF1(S)), sizeof(int32_T));
  NDTransposeBySrcSpecsMwSize((void*)passwd_t, (const void*)passwd,
    mxGetDimensions (PARAM_DEF2(S)), mxGetNumberOfDimensions(PARAM_DEF2(S)),
    sizeof(uint8_T));
  sfRedis_Update_wrapper(u0_t, y0_t, xD, pW, host_t, p_width0, port_t, p_width1,
    passwd_t, p_width2, y_0_width, u_0_width, S);
  NDTransposeByDstSpecs((void*)y0, (const void*)y0_t, ssGetOutputPortDimensions
                        (S, 0), ssGetOutputPortNumDimensions(S, 0), sizeof
                        (real_T));
}

#endif                                 /* MDL_UPDATE */

#define MDL_DERIVATIVES                                          /* Change to #undef to remove function */
#if defined(MDL_DERIVATIVES)

/* Function: mdlDerivatives =================================================
 * Abstract:
 *    In this function, you compute the S-function block's derivatives.
 *    The derivatives are placed in the derivative vector, ssGetdX(S).
 */
static void mdlDerivatives(SimStruct *S)
{
  void **pW = ssGetPWork(S);
  const real_T *u0 = (real_T *) ssGetInputPortRealSignal(S, 0);
  real_T *y0 = (real_T *) ssGetOutputPortRealSignal(S, 0);
  real_T *dx = ssGetdX(S);
  real_T *xC = ssGetContStates(S);
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const uint8_T *host = (const uint8_T *) mxGetUint8s(PARAM_DEF0(S));
  const int32_T *port = (const int32_T *) mxGetInt32s(PARAM_DEF1(S));
  const uint8_T *passwd = (const uint8_T *) mxGetUint8s(PARAM_DEF2(S));
  const int_T y_0_width = ssGetOutputPortWidth(S, 0);
  const int_T u_0_width = ssGetInputPortWidth(S, 0);

  /* S-Function Builder Row Major Support has been enabled for custom
   * code, a transposed copy will be created for any array signals.
   */
  real_T *u0_t = (real_T *)ssGetDWork(S, 0);
  real_T *y0_t = (real_T *)ssGetDWork(S, 1);
  uint8_T *host_t = (uint8_T *)ssGetDWork(S, 2);
  int32_T *port_t = (int32_T *)ssGetDWork(S, 3);
  uint8_T *passwd_t = (uint8_T *)ssGetDWork(S, 4);
  NDTransposeBySrcSpecs((void*)u0_t, (const void*)u0, ssGetInputPortDimensions(S,
    0), ssGetInputPortNumDimensions(S, 0), sizeof(real_T));
  NDTransposeBySrcSpecsMwSize((void*)host_t, (const void*)host, mxGetDimensions
    (PARAM_DEF0(S)), mxGetNumberOfDimensions(PARAM_DEF0(S)), sizeof(uint8_T));
  NDTransposeBySrcSpecsMwSize((void*)port_t, (const void*)port, mxGetDimensions
    (PARAM_DEF1(S)), mxGetNumberOfDimensions(PARAM_DEF1(S)), sizeof(int32_T));
  NDTransposeBySrcSpecsMwSize((void*)passwd_t, (const void*)passwd,
    mxGetDimensions (PARAM_DEF2(S)), mxGetNumberOfDimensions(PARAM_DEF2(S)),
    sizeof(uint8_T));
  sfRedis_Derivatives_wrapper(u0_t, y0_t, dx, xC, pW, host_t, p_width0, port_t,
    p_width1, passwd_t, p_width2, y_0_width, u_0_width, S);
  NDTransposeByDstSpecs((void*)y0, (const void*)y0_t, ssGetOutputPortDimensions
                        (S, 0), ssGetOutputPortNumDimensions(S, 0), sizeof
                        (real_T));
}

#endif                                 /* MDL_DERIVATIVES */

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
  void **pW = ssGetPWork(S);
  real_T *xD = ssGetDiscStates(S);
  real_T *xC = ssGetContStates(S);
  const int_T p_width0 = mxGetNumberOfElements(PARAM_DEF0(S));
  const int_T p_width1 = mxGetNumberOfElements(PARAM_DEF1(S));
  const int_T p_width2 = mxGetNumberOfElements(PARAM_DEF2(S));
  const uint8_T *host = (const uint8_T *) mxGetUint8s(PARAM_DEF0(S));
  const int32_T *port = (const int32_T *) mxGetInt32s(PARAM_DEF1(S));
  const uint8_T *passwd = (const uint8_T *) mxGetUint8s(PARAM_DEF2(S));
  uint8_T *host_t = (uint8_T *)ssGetDWork(S, 2);
  int32_T *port_t = (int32_T *)ssGetDWork(S, 3);
  uint8_T *passwd_t = (uint8_T *)ssGetDWork(S, 4);
  NDTransposeBySrcSpecsMwSize((void*)host_t, (const void*)host, mxGetDimensions
    (PARAM_DEF0(S)), mxGetNumberOfDimensions(PARAM_DEF0(S)), sizeof(uint8_T));
  NDTransposeBySrcSpecsMwSize((void*)port_t, (const void*)port, mxGetDimensions
    (PARAM_DEF1(S)), mxGetNumberOfDimensions(PARAM_DEF1(S)), sizeof(int32_T));
  NDTransposeBySrcSpecsMwSize((void*)passwd_t, (const void*)passwd,
    mxGetDimensions (PARAM_DEF2(S)), mxGetNumberOfDimensions(PARAM_DEF2(S)),
    sizeof(uint8_T));
  sfRedis_Terminate_wrapper(xC, xD, pW, host_t, p_width0, port_t, p_width1,
    passwd_t, p_width2, S);
}

#ifdef MATLAB_MEX_FILE                 /* Is this file being compiled as a MEX-file? */
#include "simulink.c"                  /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"                   /* Code generation registration function */
#endif
