/* Generated by S-function Builder */
#ifndef _SFREDIS_BUS_H_
#define _SFREDIS_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#include "tmwtypes.h"
#else
#include "rtwtypes.h"
#endif




#ifndef DEFINED_TYPEDEF_FOR_sfRedisBus_
#define DEFINED_TYPEDEF_FOR_sfRedisBus_ 
typedef struct {
  real_T Time;
  real_T SineWave;
} sfRedisBus;
#endif

/* Read only - ENDS */


#endif
